// Comprehensive list of g4f models from all providers
// This file contains all models that should route through /api/python/webai/v1/chat/completions

import { isDeepInfraModel as checkDeepInfra } from './deepinfra-models';

export const G4F_MODELS = [
  // Default/Auto provider models
  'claude-sonnet-4.5', 'claude-opus-4.5', 'claude-3-7-ch-exp', 'gemini-3-pro', 'gemini-3-pro-coding-32k',
  'nano-banana-pro', 'gpt-5.1-high', 'gpt-5-chat', 'gpt-oss-120b', 'gpt-oss-20b', 'gemini-2.0-flash',
  'gemini-2.5-flash', 'gemini-2.5-pro', 'kimi-k2-0905', 'kimi-k2', 'char', 'kimi-k2-thinking',
  'sonar-reasoning', 'claude-haiku', 'claude-3.5-haiku', 'claude-opus-4', 'mistral-large',
  'qwen3-coder', 'mistral-medium', 'pixtral', 'mistral-small', 'openchat-3.5', 'deepseek-v3',
  'deepseek-terminus', 'meowgpt', 'deepseek-0324', 'seed-rp', 'grok-4', 'grok-4.1',
  'grok-4.1-thinking', 'llama-4-scout', 'llama-4-maverick', 'deepseek-v3.1', 'glm-4.5-air',
  'glm-4.5', 'glm-4.6', 'glm-4.6-thinking', 'qwen3-235b', 'imagen-3', 'imagen-4', 'dall-e-3',
  'gpt-image-1', 'recraft-v3', 'sdxl', 'flux-schnell', 'flux-dev', 'flux-krea-dev', 'grok-imagine-video',
  
  // Anondrop.net models
  'openchat', 'llama', 'gpt', 'gemma', 'claude', 'deepseek', 'glm', 'kimi', 'nemotron', 'mistral',
  'grok', 'gpt-fast', 'gemini-pro', 'flux', 'sdxl', 'tts',
  
  // Audio models
  'gpt-4o-mini-audio-preview',
  
  // Azure models
  'model-router',
  
  // DeepInfra models (route to deepinfra endpoint)
  'Qwen/Qwen3-Embedding-0.6B', 'deepseek-ai/DeepSeek-R1-0528-Turbo', 'nvidia/NVIDIA-Nemotron-Nano-9B-v2',
  'Qwen/Qwen3-14B', 'Bria/replace_background', 'sentence-transformers/all-MiniLM-L6-v2',
  'NousResearch/Hermes-3-Llama-3.1-405B', 'anthropic/claude-4-sonnet', 'meta-llama/Llama-3.2-3B-Instruct',
  'deepseek-ai/DeepSeek-V3.2-Exp', 'google/gemini-2.5-pro', 'PaddlePaddle/PaddleOCR-VL-0.9B',
  'Qwen/Qwen3-235B-A22B-Instruct-2507', 'sentence-transformers/paraphrase-MiniLM-L6-v2',
  'thenlper/gte-base', 'anthropic/claude-3-7-sonnet-latest', 'openai/gpt-oss-120b-Turbo',
  'deepseek-ai/DeepSeek-R1-0528', 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
  'black-forest-labs/FLUX.1-Kontext-dev', 'black-forest-labs/FLUX-1.1-pro', 'google/embeddinggemma-300m',
  'intfloat/multilingual-e5-large', 'BAAI/bge-large-en-v1.5', 'Qwen/Qwen3-30B-A3B',
  'intfloat/e5-base-v2', 'Qwen/Qwen2.5-72B-Instruct', 'Qwen/Qwen3-Embedding-8B',
  'Qwen/Qwen-Image-Edit', 'deepseek-ai/DeepSeek-V3.1', 'Qwen/Qwen2.5-VL-32B-Instruct',
  'google/gemma-3-27b-it', 'meta-llama/Llama-3.3-70B-Instruct-Turbo', 'deepseek-ai/DeepSeek-R1-Turbo',
  'moonshotai/Kimi-K2-Thinking', 'Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo',
  'nvidia/Llama-3.1-Nemotron-70B-Instruct', 'nvidia/Llama-3.3-Nemotron-Super-49B-v1.5',
  'Bria/Bria-3.2', 'mistralai/Mistral-Small-24B-Instruct-2501', 'google/gemma-3-12b-it',
  'deepseek-ai/DeepSeek-V3-0324', 'Bria/erase_foreground', 'google/gemini-1.5-flash-8b',
  'Bria/erase', 'Qwen/Qwen3-VL-30B-A3B-Instruct', 'meta-llama/Meta-Llama-3.1-70B-Instruct',
  'nvidia/NVIDIA-Nemotron-Nano-12B-v2-VL', 'Qwen/Qwen3-235B-A22B-Thinking-2507',
  'sentence-transformers/multi-qa-mpnet-base-dot-v1', 'black-forest-labs/FLUX-1-schnell',
  'BAAI/bge-base-en-v1.5', 'Qwen/Qwen3-32B', 'Bria/expand', 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B',
  'Gryphe/MythoMax-L2-13b', 'deepseek-ai/Janus-Pro-7B', 'Bria/fibo', 'deepseek-ai/DeepSeek-OCR',
  'google/gemini-1.5-flash', 'intfloat/e5-large-v2', 'ByteDance/Seedream-4', 'microsoft/phi-4',
  'microsoft/WizardLM-2-8x22B', 'BAAI/bge-m3', 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
  'deepseek-ai/DeepSeek-V3.1-Terminus', 'zai-org/GLM-4.6', 'Bria/Bria-3.2-vector',
  'anthropic/claude-4-opus', 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'meta-llama/Llama-3.2-11B-Vision-Instruct',
  'Qwen/Qwen3-Embedding-8B-batch', 'NousResearch/Hermes-3-Llama-3.1-70B',
  'Sao10K/L3.1-70B-Euryale-v2.2', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8',
  'mistralai/Mistral-Nemo-Instruct-2407', 'black-forest-labs/FLUX-1-Redux-dev',
  'shibing624/text2vec-base-chinese', 'thenlper/gte-large', 'allenai/olmOCR-2-7B-1025',
  'deepseek-ai/Janus-Pro-1B', 'openai/gpt-oss-120b', 'BAAI/bge-en-icl',
  'mistralai/Mistral-Small-3.2-24B-Instruct-2506', 'Qwen/Qwen3-Embedding-4B-batch',
  'sentence-transformers/all-mpnet-base-v2', 'intfloat/multilingual-e5-large-instruct',
  'stabilityai/sdxl-turbo', 'black-forest-labs/FLUX-1-dev', 'Sao10K/L3-8B-Lunaris-v1-Turbo',
  'Bria/gen_fill', 'Qwen/Qwen3-Next-80B-A3B-Instruct', 'Qwen/Qwen3-Embedding-4B',
  'meta-llama/Llama-Guard-4-12B', 'sentence-transformers/clip-ViT-B-32', 'BAAI/bge-m3-multi',
  'Qwen/Qwen3-VL-235B-A22B-Instruct', 'meta-llama/Meta-Llama-3.1-8B-Instruct', 'deepseek-ai/DeepSeek-V3',
  'Bria/remove_background', 'Bria/enhance', 'google/gemini-2.0-flash-001', 'openai/gpt-oss-20b',
  'moonshotai/Kimi-K2-Instruct-0905', 'google/gemini-2.5-flash', 'google/gemma-3-4b-it',
  'Bria/blur_background', 'Qwen/Qwen3-Embedding-0.6B-batch', 'sentence-transformers/all-MiniLM-L12-v2',
  'MiniMaxAI/MiniMax-M2', 'meta-llama/Meta-Llama-3-8B-Instruct', 'black-forest-labs/FLUX-pro',
  'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', 'Sao10K/L3.3-70B-Euryale-v2.3',
  'meta-llama/Llama-4-Scout-17B-16E-Instruct', 'deepseek-ai/DeepSeek-R1',
  'sentence-transformers/clip-ViT-B-32-multilingual-v1',
  
  // Gemini models
  'models/embedding-gecko-001', 'models/gemini-2.5-pro-preview-03-25', 'models/gemini-2.5-flash',
  'models/gemini-2.5-pro-preview-05-06', 'models/gemini-2.5-pro-preview-06-05', 'models/gemini-2.5-pro',
  'models/gemini-2.0-flash-exp', 'models/gemini-2.0-flash', 'models/gemini-2.0-flash-001',
  'models/gemini-2.0-flash-exp-image-generation', 'models/gemini-2.0-flash-lite-001',
  'models/gemini-2.0-flash-lite', 'models/gemini-2.0-flash-lite-preview-02-05',
  'models/gemini-2.0-flash-lite-preview', 'models/gemini-2.0-pro-exp', 'models/gemini-2.0-pro-exp-02-05',
  'models/gemini-exp-1206', 'models/gemini-2.0-flash-thinking-exp-01-21', 'models/gemini-2.0-flash-thinking-exp',
  'models/gemini-2.0-flash-thinking-exp-1219', 'models/gemini-2.5-flash-preview-tts',
  'models/gemini-2.5-pro-preview-tts', 'models/learnlm-2.0-flash-experimental', 'models/gemma-3-1b-it',
  'models/gemma-3-4b-it', 'models/gemma-3-12b-it', 'models/gemma-3-27b-it', 'models/gemma-3n-e4b-it',
  'models/gemma-3n-e2b-it', 'models/gemini-flash-latest', 'models/gemini-flash-lite-latest',
  'models/gemini-pro-latest', 'models/gemini-2.5-flash-lite', 'models/gemini-2.5-flash-image-preview',
  'models/gemini-2.5-flash-image', 'models/gemini-2.5-flash-preview-09-2025',
  'models/gemini-2.5-flash-lite-preview-09-2025', 'models/gemini-3-pro-preview',
  'models/gemini-3-pro-image-preview', 'models/nano-banana-pro-preview', 'models/gemini-robotics-er-1.5-preview',
  'models/gemini-2.5-computer-use-preview-10-2025', 'models/embedding-001', 'models/text-embedding-004',
  'models/gemini-embedding-exp-03-07', 'models/gemini-embedding-exp', 'models/gemini-embedding-001',
  'models/aqa', 'models/imagen-4.0-generate-preview-06-06', 'models/imagen-4.0-ultra-generate-preview-06-06',
  'models/imagen-4.0-generate-001', 'models/imagen-4.0-ultra-generate-001', 'models/imagen-4.0-fast-generate-001',
  'models/veo-2.0-generate-001', 'models/veo-3.0-generate-001', 'models/veo-3.0-fast-generate-001',
  'models/veo-3.1-generate-preview', 'models/veo-3.1-fast-generate-preview', 'models/gemini-2.0-flash-live-001',
  'models/gemini-live-2.5-flash-preview', 'models/gemini-2.5-flash-live-preview',
  'models/gemini-2.5-flash-native-audio-latest', 'models/gemini-2.5-flash-native-audio-preview-09-2025',
  'models/lyria-realtime-exp',
  
  // GPT-OSS-120B
  'gpt-oss-120b',
  
  // GPT4Free.pro models
  'deepseek-v3.1', 'command-a', 'seed-oss', 'flux-schnell', 'deepseek-chat', 'deepseek-reasoner',
  'glm-4.6', 'gpt-5-nano', 'o1-pro', 'claude-sonnet-4', 'claude-3-7-sonnet', 'claude-sonnet-4.5',
  'claude-haiku-4.5', 'hermes-4-405b', 'hermes-3-405b', 'qwen3-coder', 'qwen3-coder-big',
  'qwq-32b-fast', 'gpt-oss-120b', 'llama-3.3', 'nova-micro', 'nova-lite', 'nova-pro', 'kimi-k2',
  'kimi-k2-0905', 'llama-4-maverick', 'llama-4-scout', 'gemini-2.5-flash-lite', 'gemini-2.5-flash',
  'gemini-2.5-pro', 'lucid-origin', 'sdxl', 'cogvideox-flash', 'nano-banana', 'grok-4', 'grok-4-think',
  'grok-code-1', 'grok-3-mini', 'gpt-image-1', 'gpt-5-chat', 'gpt-5-mini', 'qwen2.5-coder-32b',
  'qwen3-omni', 'qwen3-next', 'deepseek-r1-0528', 'mistral-small-3.1-24b', 'gpt-4.1-mini',
  'gpt-4.1-nano', 'o4-mini', 'o3-mini', 'gpt-4o-mini', 'gpt-3.5-turbo', 'deepseek-v3', 'deepseek-v3.2',
  'deepseek-r1', 'glm-4.5', 'glm-4.5-air', 'ring-1t', 'ling-1t', 'ernie-4.5', 'sonar', 'mistral-medium-3',
  'goliath-120b', 'sd-3.5', 'sd-3.5-large', 'dall-e-3', 'cliptagger-12b', 'gemma-3n-e4b',
  'nemotron-ultra-235b',
  
  // Groq models
  'groq/compound', 'openai/gpt-oss-safeguard-20b', 'whisper-large-v3-turbo', 'playai-tts-arabic',
  'meta-llama/llama-guard-4-12b', 'qwen/qwen3-32b', 'moonshotai/kimi-k2-instruct', 'whisper-large-v3',
  'meta-llama/llama-prompt-guard-2-86m', 'openai/gpt-oss-120b', 'llama-3.3-70b-versatile',
  'allam-2-7b', 'openai/gpt-oss-20b', 'meta-llama/llama-4-maverick-17b-128e-instruct',
  'groq/compound-mini', 'llama-3.1-8b-instant', 'meta-llama/llama-4-scout-17b-16e-instruct',
  'playai-tts', 'meta-llama/llama-prompt-guard-2-22m', 'moonshotai/kimi-k2-instruct-0905',
  
  // HuggingFace models (191+ models - sample list)
  'moonshotai/Kimi-K2-Thinking', 'deepseek-ai/DeepSeek-OCR', 'allenai/Olmo-3-7B-Instruct',
  'meta-llama/Llama-3.1-8B-Instruct', 'openai/gpt-oss-20b', 'MiniMaxAI/MiniMax-M2',
  'deepcogito/cogito-671b-v2.1', 'zai-org/GLM-4.6', 'openai/gpt-oss-120b', 'Qwen/Qwen3-VL-8B-Instruct',
  'google/gemma-3-27b-it', 'Qwen/Qwen2.5-7B-Instruct', 'Qwen/Qwen3-8B', 'Qwen/Qwen3-VL-30B-A3B-Instruct',
  'deepseek-ai/DeepSeek-V3.2-Exp', 'meta-llama/Llama-3.2-3B-Instruct', 'deepseek-ai/DeepSeek-R1',
  'meta-llama/Meta-Llama-3-8B-Instruct', 'Qwen/Qwen2.5-VL-7B-Instruct', 'moonshotai/Kimi-K2-Instruct',
  'Qwen/Qwen3-Coder-30B-A3B-Instruct', 'Qwen/Qwen3-Next-80B-A3B-Instruct', 'Qwen/Qwen2.5-1.5B-Instruct',
  'meta-llama/Llama-3.2-1B-Instruct', 'Qwen/Qwen3-4B-Instruct-2507', 'nvidia/NVIDIA-Nemotron-Nano-12B-v2',
  'Qwen/Qwen3-1.7B', 'Qwen/Qwen3-30B-A3B-Instruct-2507', 'meta-llama/Llama-3.1-70B-Instruct',
  'meta-llama/Llama-3.3-70B-Instruct', 'Qwen/Qwen3-32B', 'Qwen/Qwen3-4B-Thinking-2507',
  'HuggingFaceTB/SmolLM3-3B', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B',
  'dphn/Dolphin-Mistral-24B-Venice-Edition', 'deepcogito/cogito-671b-v2.1-FP8',
  'google/gemma-3-12b-it', 'mlabonne/gemma-3-27b-it-abliterated', 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
  'Qwen/QwQ-32B', 'Qwen/Qwen3-30B-A3B', 'moonshotai/Kimi-K2-Instruct-0905',
  'mistralai/Mistral-7B-Instruct-v0.2', 'MLP-KTLim/llama-3-Korean-Bllossom-8B', 'google/gemma-2-2b-it',
  'Qwen/Qwen2.5-72B-Instruct', 'Qwen/Qwen2.5-VL-72B-Instruct', 'baichuan-inc/Baichuan-M2-32B',
  'Qwen/Qwen3-VL-235B-A22B-Instruct', 'deepseek-ai/DeepSeek-V3.1-Terminus',
  'HuggingFaceH4/zephyr-7b-beta', 'm42-health/Llama3-Med42-8B', 'inflatebot/MN-12B-Mag-Mell-R1',
  'deepseek-ai/DeepSeek-V3', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B',
  'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct',
  'DeepHat/DeepHat-V1-7B', 'Qwen/Qwen3-235B-A22B', 'ReadyArt/Broken-Tutu-24B',
  'darkc0de/XortronCriminalComputingConfig', 'deepseek-ai/DeepSeek-R1-0528-Qwen3-8B',
  'zai-org/GLM-4.5', 'Qwen/Qwen3-235B-A22B-Instruct-2507', 'NousResearch/Hermes-4-405B',
  'swiss-ai/Apertus-8B-Instruct-2509', 'Qwen/Qwen3-VL-235B-A22B-Thinking',
  'IlyaGusev/saiga_llama3_8b', 'Orenguteng/Llama-3-8B-Lexi-Uncensored',
  'NousResearch/Hermes-2-Pro-Llama-3-8B', 'Qwen/Qwen2-1.5B-Instruct', 'Sao10K/L3-70B-Euryale-v2.1',
  'Luni/StarDust-12b-v2', 'Qwen/Qwen2.5-1.5B', 'Qwen/Qwen2.5-7B', 'Qwen/Qwen2.5-Coder-7B-Instruct',
  'Qwen/Qwen2.5-Coder-1.5B-Instruct', 'Orion-zhen/Qwen2.5-7B-Instruct-Uncensored',
  'EVA-UNIT-01/EVA-Qwen2.5-32B-v0.2', 'FallenMerick/MN-Violet-Lotus-12B',
  'deepseek-ai/DeepSeek-R1-Distill-Llama-8B', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
  'deepseek-ai/DeepSeek-V3-0324', 'meta-llama/Llama-4-Scout-17B-16E-Instruct',
  'nvidia/OpenMath-Nemotron-14B-Kaggle', 'Qwen/Qwen3-14B', 'Qwen/Qwen3-14B-Base',
  'Intelligent-Internet/II-Medical-8B', 'marin-community/marin-8b-instruct', 'ArliAI/QwQ-32B-ArliAI-RpR-v4',
  'zai-org/GLM-4.5-Air', 'zai-org/GLM-4.5-Air-FP8', 'zai-org/GLM-4.5V',
  'Qwen/Qwen3-Next-80B-A3B-Thinking', 'zai-org/GLM-4.6-FP8', 'inclusionAI/Ling-1T',
  'meta-llama/Llama-2-13b-chat-hf', 'HuggingFaceH4/zephyr-7b-alpha', 'ceadar-ie/FinanceConnect-13B',
  'Qwen/Qwen1.5-1.8B-Chat', 'GritLM/GritLM-7B', 'meta-llama/Meta-Llama-3-70B-Instruct',
  'beomi/Llama-3-KoEn-8B', 'QuixiAI/Llama-3-8B-Instruct-abliterated-v2',
  'failspy/Meta-Llama-3-8B-Instruct-abliterated-v3', 'Henrychur/MMed-Llama-3-8B',
  'Qwen/Qwen2-7B-Instruct', 'Sao10K/L3-8B-Stheno-v3.2', 'LLaMAX/LLaMAX3-8B-Alpaca',
  'SeaLLMs/SeaLLMs-v3-7B-Chat', 'unsloth/gemma-2-9b-it', 'pentagoniac/SEMIKONG-70B',
  'meta-llama/Llama-3.1-405B-Instruct', 'unsloth/Meta-Llama-3.1-8B-Instruct',
  'SeaLLMs/SeaLLMs-v3-7B', 'aifeifei798/DarkIdol-Llama-3.1-8B-Instruct-1.2-Uncensored',
  'NousResearch/Hermes-3-Llama-3.1-8B', 'nothingiisreal/MN-12B-Celeste-V1.9',
  'anthracite-org/magnum-v2-12b', 'vicgalle/Humanish-Roleplay-Llama-3.1-8B',
  'Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2', 'nvidia/Llama-3.1-8B-Instruct-FP8',
  'nvidia/Llama-3.1-70B-Instruct-FP8', 'Qwen/Qwen2.5-14B-Instruct', 'Qwen/Qwen2.5-Coder-7B',
  'Qwen/Qwen2.5-Math-1.5B-Instruct', 'Qwen/Qwen2.5-32B-Instruct', 'Qwen/Qwen2.5-Math-7B-Instruct',
  'google/gemma-2-2b-jpn-it', 'huihui-ai/Qwen2.5-32B-Instruct-abliterated',
  'LyraNovaHeart/Stellar-Odyssey-12b-v0.0', 'DavidAU/MN-GRAND-Gutenberg-Lyra4-Lyra-12B-MADNESS',
  'anthracite-org/magnum-v4-12b', 'PygmalionAI/Pygmalion-3-12B', 'Qwen/Qwen2.5-Coder-3B-Instruct',
  'Qwen/Qwen2.5-Coder-14B-Instruct', 'AIDC-AI/Marco-o1', 'Sao10K/72B-Qwen2.5-Kunou-v1',
  'CohereLabs/c4ai-command-r7b-12-2024', 'scb10x/typhoon2-qwen2.5-7b-instruct',
  'Sao10K/32B-Qwen2.5-Kunou-v1', 'Steelskull/L3.3-MS-Nevoria-70b',
  'mlfoundations-dev/oh-dcft-v3.1-claude-3-5-sonnet-20241022', 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B',
  'bespokelabs/Bespoke-Stratos-7B', 'huihui-ai/DeepSeek-R1-Distill-Qwen-32B-abliterated',
  'karakuri-ai/karakuri-lm-32b-thinking-2501-exp', 'Qwen/Qwen2.5-7B-Instruct-1M',
  'Delta-Vector/Archaeo-12B', 'simplescaling/s1.1-32B', 'NousResearch/DeepHermes-3-Llama-3-8B-Preview',
  'open-thoughts/OpenThinker-32B', 'PocketDoc/Dans-PersonalityEngine-V1.2.0-24b',
  'qihoo360/TinyR1-32B-Preview', 'yamatazen/EtherealAurora-12B', 'Steelskull/L3.3-Electra-R1-70b',
  'huihui-ai/QwQ-32B-abliterated', 'mistralai/Mistral-Small-3.1-24B-Instruct-2503',
  'unsloth/gemma-3-27b-it', 'Qwen/Qwen2.5-VL-32B-Instruct',
  'Mantis2024/Dirty-Shirley-Writer-v01-Uncensored', 'allura-org/Gemma-3-Glitter-12B',
  'Salesforce/Llama-xLAM-2-8b-fc-r', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8',
  'zai-org/GLM-4-32B-0414', 'ReadyArt/Omega-Darker-Gaslight_The-Final-Forgotten-Fever-Dream-24B',
  'nvidia/OpenMath-Nemotron-7B', 'nvidia/OpenMath-Nemotron-32B', 'Tesslate/UIGEN-T2-7B',
  'Goekdeniz-Guelmez/Josiefied-Qwen3-8B-abliterated-v1', 'mlabonne/Qwen3-8B-abliterated',
  'microsoft/NextCoder-32B', 'PocketDoc/Dans-PersonalityEngine-V1.3.0-24b',
  'PocketDoc/Dans-PersonalityEngine-V1.3.0-12b', 'ReadyArt/Broken-Tutu-24B-Unslop-v2.0',
  'Menlo/Jan-nano', 'ReadyArt/Broken-Tutu-24B-Transgression-v2.0',
  'tokyotech-llm/Llama-3.1-Swallow-8B-Instruct-v0.5', 'Retreatcost/KansenSakura-Zero-RP-12b',
  'baidu/ERNIE-4.5-0.3B-PT', 'agentica-org/DeepSWE-Preview', 'nvidia/OpenReasoning-Nemotron-7B',
  'Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8', 'Qwen/Qwen3-235B-A22B-Thinking-2507',
  'CohereLabs/command-a-vision-07-2025', 'fdtn-ai/Foundation-Sec-8B-Instruct',
  'Qwen/Qwen3-30B-A3B-Thinking-2507', 'deepseek-ai/DeepSeek-V3.1',
  'swiss-ai/Apertus-70B-Instruct-2509', 'openai/gpt-oss-safeguard-20b', 'Qwen/Qwen3-VL-30B-A3B-Thinking',
  'aisingapore/Qwen-SEA-LION-v4-32B-IT', 'VIDraft/Gemma-3-R1984-12B', 'NeverSleep/Lumimaid-v0.2-8B',
  'sophosympatheia/Strawberrylemonade-L3-70B-v1.1', 'google/gemma-3-27b-it',
  
  // NVIDIA models (165+ models - sample list)
  '01-ai/yi-large', 'abacusai/dracarys-llama-3.1-70b-instruct', 'adept/fuyu-8b',
  'ai21labs/jamba-1.5-large-instruct', 'ai21labs/jamba-1.5-mini-instruct',
  'aisingapore/sea-lion-7b-instruct', 'baai/bge-m3', 'baichuan-inc/baichuan2-13b-chat',
  'bigcode/starcoder2-15b', 'bigcode/starcoder2-7b', 'bytedance/seed-oss-36b-instruct',
  'databricks/dbrx-instruct', 'deepseek-ai/deepseek-coder-6.7b-instruct', 'deepseek-ai/deepseek-r1',
  'deepseek-ai/deepseek-r1-0528', 'deepseek-ai/deepseek-r1-distill-llama-8b',
  'deepseek-ai/deepseek-r1-distill-qwen-14b', 'deepseek-ai/deepseek-r1-distill-qwen-32b',
  'deepseek-ai/deepseek-r1-distill-qwen-7b', 'deepseek-ai/deepseek-v3.1',
  'deepseek-ai/deepseek-v3.1-terminus', 'google/codegemma-1.1-7b', 'google/codegemma-7b',
  'google/deplot', 'google/gemma-2-27b-it', 'google/gemma-2-2b-it', 'google/gemma-2-9b-it',
  'google/gemma-2b', 'google/gemma-3-12b-it', 'google/gemma-3-1b-it', 'google/gemma-3-27b-it',
  'google/gemma-3-4b-it', 'google/gemma-3n-e2b-it', 'google/gemma-3n-e4b-it', 'google/gemma-7b',
  'google/paligemma', 'google/recurrentgemma-2b', 'google/shieldgemma-9b',
  'gotocompany/gemma-2-9b-cpt-sahabatai-instruct', 'ibm/granite-3.0-3b-a800m-instruct',
  'ibm/granite-3.0-8b-instruct', 'ibm/granite-3.3-8b-instruct', 'ibm/granite-34b-code-instruct',
  'ibm/granite-8b-code-instruct', 'ibm/granite-guardian-3.0-8b', 'igenius/colosseum_355b_instruct_16k',
  'igenius/italia_10b_instruct_16b', 'institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1',
  'institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1', 'marin/marin-8b-instruct',
  'mediatek/breeze-7b-instruct', 'meta/codellama-70b', 'meta/llama-3.1-405b-instruct',
  'meta/llama-3.1-70b-instruct', 'meta/llama-3.1-8b-instruct', 'meta/llama-3.2-11b-vision-instruct',
  'meta/llama-3.2-1b-instruct', 'meta/llama-3.2-3b-instruct', 'meta/llama-3.2-90b-vision-instruct',
  'meta/llama-3.3-70b-instruct', 'meta/llama-4-maverick-17b-128e-instruct',
  'meta/llama-4-scout-17b-16e-instruct', 'meta/llama-guard-4-12b', 'meta/llama2-70b',
  'meta/llama3-70b-instruct', 'meta/llama3-8b-instruct', 'microsoft/kosmos-2',
  'microsoft/phi-3-medium-128k-instruct', 'microsoft/phi-3-medium-4k-instruct',
  'microsoft/phi-3-mini-128k-instruct', 'microsoft/phi-3-mini-4k-instruct',
  'microsoft/phi-3-small-128k-instruct', 'microsoft/phi-3-small-8k-instruct',
  'microsoft/phi-3-vision-128k-instruct', 'microsoft/phi-3.5-mini-instruct',
  'microsoft/phi-3.5-moe-instruct', 'microsoft/phi-3.5-vision-instruct', 'microsoft/phi-4-mini-flash-reasoning',
  'microsoft/phi-4-mini-instruct', 'microsoft/phi-4-multimodal-instruct', 'minimaxai/minimax-m2',
  'mistralai/codestral-22b-instruct-v0.1', 'mistralai/magistral-small-2506',
  'mistralai/mamba-codestral-7b-v0.1', 'mistralai/mathstral-7b-v0.1', 'mistralai/mistral-7b-instruct-v0.2',
  'mistralai/mistral-7b-instruct-v0.3', 'mistralai/mistral-large', 'mistralai/mistral-large-2-instruct',
  'mistralai/mistral-medium-3-instruct', 'mistralai/mistral-nemotron', 'mistralai/mistral-small-24b-instruct',
  'mistralai/mistral-small-3.1-24b-instruct-2503', 'mistralai/mixtral-8x22b-instruct-v0.1',
  'mistralai/mixtral-8x22b-v0.1', 'mistralai/mixtral-8x7b-instruct-v0.1', 'moonshotai/kimi-k2-instruct',
  'moonshotai/kimi-k2-instruct-0905', 'nv-mistralai/mistral-nemo-12b-instruct',
  'nvidia/embed-qa-4', 'nvidia/llama-3.1-nemoguard-8b-content-safety',
  'nvidia/llama-3.1-nemoguard-8b-topic-control', 'nvidia/llama-3.1-nemotron-51b-instruct',
  'nvidia/llama-3.1-nemotron-70b-instruct', 'nvidia/llama-3.1-nemotron-70b-reward',
  'nvidia/llama-3.1-nemotron-nano-4b-v1.1', 'nvidia/llama-3.1-nemotron-nano-8b-v1',
  'nvidia/llama-3.1-nemotron-nano-vl-8b-v1', 'nvidia/llama-3.1-nemotron-safety-guard-8b-v3',
  'nvidia/llama-3.1-nemotron-ultra-253b-v1', 'nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1',
  'nvidia/llama-3.2-nemoretriever-300m-embed-v1', 'nvidia/llama-3.2-nemoretriever-300m-embed-v2',
  'nvidia/llama-3.2-nv-embedqa-1b-v1', 'nvidia/llama-3.2-nv-embedqa-1b-v2',
  'nvidia/llama-3.3-nemotron-super-49b-v1', 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
  'nvidia/llama3-chatqa-1.5-70b', 'nvidia/llama3-chatqa-1.5-8b', 'nvidia/mistral-nemo-minitron-8b-8k-instruct',
  'nvidia/mistral-nemo-minitron-8b-base', 'nvidia/nemoretriever-parse', 'nvidia/nemotron-4-340b-instruct',
  'nvidia/nemotron-4-340b-reward', 'nvidia/nemotron-4-mini-hindi-4b-instruct', 'nvidia/nemotron-mini-4b-instruct',
  'nvidia/nemotron-nano-12b-v2-vl', 'nvidia/nemotron-parse', 'nvidia/neva-22b', 'nvidia/nv-embed-v1',
  'nvidia/nv-embedcode-7b-v1', 'nvidia/nv-embedqa-e5-v5', 'nvidia/nv-embedqa-mistral-7b-v2',
  'nvidia/nvclip', 'nvidia/nvidia-nemotron-nano-9b-v2', 'nvidia/riva-translate-4b-instruct',
  'nvidia/usdcode-llama-3.1-70b-instruct', 'nvidia/vila', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b',
  'opengpt-x/teuken-7b-instruct-commercial-v0.4', 'qwen/qwen2-7b-instruct', 'qwen/qwen2.5-7b-instruct',
  'qwen/qwen2.5-coder-32b-instruct', 'qwen/qwen2.5-coder-7b-instruct', 'qwen/qwen3-235b-a22b',
  'qwen/qwen3-coder-480b-a35b-instruct', 'qwen/qwen3-next-80b-a3b-instruct',
  'qwen/qwen3-next-80b-a3b-thinking', 'qwen/qwq-32b', 'rakuten/rakutenai-7b-chat',
  'rakuten/rakutenai-7b-instruct', 'sarvamai/sarvam-m', 'snowflake/arctic-embed-l',
  'speakleash/bielik-11b-v2.3-instruct', 'speakleash/bielik-11b-v2.6-instruct',
  'stockmark/stockmark-2-100b-instruct', 'thudm/chatglm3-6b', 'tiiuae/falcon3-7b-instruct',
  'tokyotech-llm/llama-3-swallow-70b-instruct-v0.1', 'upstage/solar-10.7b-instruct',
  'utter-project/eurollm-9b-instruct', 'writer/palmyra-creative-122b', 'writer/palmyra-fin-70b-32k',
  'writer/palmyra-med-70b', 'writer/palmyra-med-70b-32k', 'yentinglin/llama-3-taiwan-70b-instruct',
  'zyphra/zamba2-7b-instruct',
  
  // Ollama models
  'cogito-2.1:671b', 'glm-4.6', 'kimi-k2:1t', 'kimi-k2-thinking', 'qwen3-coder:480b',
  'deepseek-v3.1:671b', 'gpt-oss:120b', 'gpt-oss:20b', 'qwen3-vl:235b-instruct',
  'qwen3-vl:235b', 'minimax-m2', 'gemini-3-pro-preview',
  
  // OpenRouter models (36+ models)
  'x-ai/grok-4.1-fast:free', 'kwaipilot/kat-coder-pro:free', 'nvidia/nemotron-nano-12b-v2-vl:free',
  'alibaba/tongyi-deepresearch-30b-a3b:free', 'meituan/longcat-flash-chat:free',
  'nvidia/nemotron-nano-9b-v2:free', 'openai/gpt-oss-20b:free', 'z-ai/glm-4.5-air:free',
  'qwen/qwen3-coder:free', 'moonshotai/kimi-k2:free', 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free',
  'google/gemma-3n-e2b-it:free', 'tngtech/deepseek-r1t2-chimera:free',
  'mistralai/mistral-small-3.2-24b-instruct:free', 'deepseek/deepseek-r1-0528-qwen3-8b:free',
  'deepseek/deepseek-r1-0528:free', 'google/gemma-3n-e4b-it:free', 'qwen/qwen3-4b:free',
  'qwen/qwen3-30b-a3b:free', 'qwen/qwen3-14b:free', 'qwen/qwen3-235b-a22b:free',
  'tngtech/deepseek-r1t-chimera:free', 'microsoft/mai-ds-r1:free', 'arliai/qwq-32b-arliai-rpr-v1:free',
  'qwen/qwen2.5-vl-32b-instruct:free', 'deepseek/deepseek-chat-v3-0324:free',
  'mistralai/mistral-small-3.1-24b-instruct:free', 'google/gemma-3-4b-it:free',
  'google/gemma-3-12b-it:free', 'google/gemma-3-27b-it:free', 'mistralai/mistral-small-24b-instruct-2501:free',
  'deepseek/deepseek-r1-distill-llama-70b:free', 'deepseek/deepseek-r1:free',
  'google/gemini-2.0-flash-exp:free', 'meta-llama/llama-3.3-70b-instruct:free',
  'qwen/qwen-2.5-coder-32b-instruct:free', 'meta-llama/llama-3.2-3b-instruct:free',
  'qwen/qwen-2.5-72b-instruct:free', 'nousresearch/hermes-3-llama-3.1-405b:free',
  'mistralai/mistral-nemo:free', 'mistralai/mistral-7b-instruct:free',
  
  // Pollinations.ai models
  'deepseek-v3', 'gemini-2.5-flash-lite', 'searchgpt', 'mistral-small-3.1-24b-instruct',
  'gpt-5-mini', 'gpt-4o-mini-audio-preview', 'gpt-5-nano', 'o4-mini', 'qwen2.5-coder-32b-instruct',
  'llama-roblox', 'bidara', 'chickytutor', 'evil', 'midijourney', 'rtist', 'unity', 'flux', 'sdxl-turbo',
  'gpt-image',
  
  // Puter models (436+ models)
  'gpt-5.1', 'gpt-5.1-codex', 'gpt-5.1-codex-mini', 'gpt-5.1-chat-latest', 'gpt-5-2025-08-07',
  'gpt-5', 'gpt-5-mini-2025-08-07', 'gpt-5-mini', 'gpt-5-nano-2025-08-07', 'gpt-5-nano',
  'gpt-5-chat-latest', 'gpt-4o', 'gpt-4o-mini', 'o1', 'o1-mini', 'o1-pro', 'o3', 'o3-mini', 'o4-mini',
  'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'gpt-4.5-preview', 'claude-opus-4-5', 'claude-opus-4-5-latest',
  'claude-opus-4.5', 'claude-haiku-4-5-20251001', 'claude-haiku-4.5', 'claude-haiku-4-5',
  'claude-sonnet-4-5-20250929', 'claude-sonnet-4.5', 'claude-sonnet-4-5', 'claude-opus-4-1-20250805',
  'claude-opus-4-1', 'claude-opus-4-20250514', 'claude-opus-4', 'claude-opus-4-latest',
  'claude-sonnet-4-20250514', 'claude-sonnet-4', 'claude-sonnet-4-latest', 'claude-3-7-sonnet-20250219',
  'claude-3-7-sonnet-latest', 'claude-3-5-sonnet-20241022', 'claude-3-5-sonnet-latest',
  'claude-3-5-sonnet-20240620', 'claude-3-haiku-20240307', 'mistral-large-latest', 'mistral-medium-2508',
  'mistral-medium-latest', 'mistral-medium', 'ministral-3b-2410', 'ministral-3b-latest', 'ministral-8b-2410',
  'ministral-8b-latest', 'open-mistral-7b', 'mistral-tiny', 'mistral-tiny-2312', 'open-mistral-nemo',
  'open-mistral-nemo-2407', 'mistral-tiny-2407', 'mistral-tiny-latest', 'pixtral-large-2411',
  'pixtral-large-latest', 'mistral-large-pixtral-2411', 'codestral-2508', 'codestral-latest',
  'devstral-small-2507', 'devstral-small-latest', 'pixtral-12b-2409', 'pixtral-12b', 'pixtral-12b-latest',
  'mistral-small-2506', 'mistral-small-latest', 'magistral-medium-2509', 'magistral-medium-latest',
  'magistral-small-2509', 'magistral-small-latest', 'mistral-moderation-2411', 'mistral-moderation-latest',
  'mistral-ocr-2505', 'mistral-ocr-latest', 'grok-beta', 'grok-vision-beta', 'grok-3', 'grok-3-fast',
  'grok-3-mini', 'grok-3-mini-fast', 'grok-2-vision', 'grok-2', 'deepseek-chat', 'deepseek-reasoner',
  'gemini-1.5-flash', 'gemini-2.0-flash', 'gemini-2.0-flash-lite', 'gemini-2.5-flash', 'gemini-2.5-flash-lite',
  'gemini-2.5-pro', 'gemini-3-pro-preview',
  // OpenRouter models (with openrouter: prefix - these should work without prefix too)
  'openrouter:anthropic/claude-opus-4.5', 'openrouter:openrouter/bert-nebulon-alpha', 'openrouter:allenai/olmo-3-32b-think',
  'openrouter:allenai/olmo-3-7b-instruct', 'openrouter:allenai/olmo-3-7b-think', 'openrouter:google/gemini-3-pro-image-preview',
  'openrouter:x-ai/grok-4.1-fast', 'openrouter:google/gemini-3-pro-preview', 'openrouter:deepcogito/cogito-v2.1-671b',
  'openrouter:openai/gpt-5.1', 'openrouter:openai/gpt-5.1-chat', 'openrouter:openai/gpt-5.1-codex',
  'openrouter:openai/gpt-5.1-codex-mini', 'openrouter:kwaipilot/kat-coder-pro:free', 'openrouter:moonshotai/kimi-linear-48b-a3b-instruct',
  'openrouter:moonshotai/kimi-k2-thinking', 'openrouter:amazon/nova-premier-v1', 'openrouter:perplexity/sonar-pro-search',
  'openrouter:mistralai/voxtral-small-24b-2507', 'openrouter:openai/gpt-oss-safeguard-20b', 'openrouter:nvidia/nemotron-nano-12b-v2-vl:free',
  'openrouter:nvidia/nemotron-nano-12b-v2-vl', 'openrouter:minimax/minimax-m2', 'openrouter:liquid/lfm2-8b-a1b',
  'openrouter:liquid/lfm-2.2-6b', 'openrouter:ibm-granite/granite-4.0-h-micro', 'openrouter:deepcogito/cogito-v2-preview-llama-405b',
  'openrouter:openai/gpt-5-image-mini', 'openrouter:anthropic/claude-haiku-4.5', 'openrouter:qwen/qwen3-vl-8b-thinking',
  'openrouter:qwen/qwen3-vl-8b-instruct', 'openrouter:openai/gpt-5-image', 'openrouter:openai/o3-deep-research',
  'openrouter:openai/o4-mini-deep-research', 'openrouter:nvidia/llama-3.3-nemotron-super-49b-v1.5',
  'openrouter:baidu/ernie-4.5-21b-a3b-thinking', 'openrouter:google/gemini-2.5-flash-image',
  'openrouter:qwen/qwen3-vl-30b-a3b-thinking', 'openrouter:qwen/qwen3-vl-30b-a3b-instruct',
  'openrouter:openai/gpt-5-pro', 'openrouter:z-ai/glm-4.6', 'openrouter:z-ai/glm-4.6:exacto',
  'openrouter:anthropic/claude-sonnet-4.5', 'openrouter:deepseek/deepseek-v3.2-exp', 'openrouter:thedrummer/cydonia-24b-v4.1',
  'openrouter:relace/relace-apply-3', 'openrouter:google/gemini-2.5-flash-preview-09-2025',
  'openrouter:google/gemini-2.5-flash-lite-preview-09-2025', 'openrouter:qwen/qwen3-vl-235b-a22b-thinking',
  'openrouter:qwen/qwen3-vl-235b-a22b-instruct', 'openrouter:qwen/qwen3-max', 'openrouter:qwen/qwen3-coder-plus',
  'openrouter:openai/gpt-5-codex', 'openrouter:deepseek/deepseek-v3.1-terminus:exacto',
  'openrouter:deepseek/deepseek-v3.1-terminus', 'openrouter:x-ai/grok-4-fast', 'openrouter:alibaba/tongyi-deepresearch-30b-a3b:free',
  'openrouter:alibaba/tongyi-deepresearch-30b-a3b', 'openrouter:qwen/qwen3-coder-flash', 'openrouter:opengvlab/internvl3-78b',
  'openrouter:qwen/qwen3-next-80b-a3b-thinking', 'openrouter:qwen/qwen3-next-80b-a3b-instruct',
  'openrouter:meituan/longcat-flash-chat:free', 'openrouter:meituan/longcat-flash-chat',
  'openrouter:qwen/qwen-plus-2025-07-28', 'openrouter:qwen/qwen-plus-2025-07-28:thinking',
  'openrouter:nvidia/nemotron-nano-9b-v2:free', 'openrouter:nvidia/nemotron-nano-9b-v2',
  'openrouter:moonshotai/kimi-k2-0905', 'openrouter:moonshotai/kimi-k2-0905:exacto',
  'openrouter:deepcogito/cogito-v2-preview-llama-70b', 'openrouter:deepcogito/cogito-v2-preview-llama-109b-moe',
  'openrouter:deepcogito/cogito-v2-preview-deepseek-671b', 'openrouter:stepfun-ai/step3',
  'openrouter:qwen/qwen3-30b-a3b-thinking-2507', 'openrouter:x-ai/grok-code-fast-1',
  'openrouter:nousresearch/hermes-4-70b', 'openrouter:nousresearch/hermes-4-405b',
  'openrouter:google/gemini-2.5-flash-image-preview', 'openrouter:deepseek/deepseek-chat-v3.1',
  'openrouter:openai/gpt-4o-audio-preview', 'openrouter:mistralai/mistral-medium-3.1',
  'openrouter:baidu/ernie-4.5-21b-a3b', 'openrouter:baidu/ernie-4.5-vl-28b-a3b', 'openrouter:z-ai/glm-4.5v',
  'openrouter:ai21/jamba-mini-1.7', 'openrouter:ai21/jamba-large-1.7', 'openrouter:openai/gpt-5-chat',
  'openrouter:openai/gpt-5', 'openrouter:openai/gpt-5-mini', 'openrouter:openai/gpt-5-nano',
  'openrouter:openai/gpt-oss-120b:exacto', 'openrouter:openai/gpt-oss-120b', 'openrouter:openai/gpt-oss-20b:free',
  'openrouter:openai/gpt-oss-20b', 'openrouter:anthropic/claude-opus-4.1', 'openrouter:mistralai/codestral-2508',
  'openrouter:qwen/qwen3-coder-30b-a3b-instruct', 'openrouter:qwen/qwen3-30b-a3b-instruct-2507',
  'openrouter:z-ai/glm-4.5', 'openrouter:z-ai/glm-4.5-air:free', 'openrouter:z-ai/glm-4.5-air',
  'openrouter:qwen/qwen3-235b-a22b-thinking-2507', 'openrouter:z-ai/glm-4-32b', 'openrouter:qwen/qwen3-coder:free',
  'openrouter:qwen/qwen3-coder', 'openrouter:qwen/qwen3-coder:exacto', 'openrouter:bytedance/ui-tars-1.5-7b',
  'openrouter:google/gemini-2.5-flash-lite', 'openrouter:qwen/qwen3-235b-a22b-2507',
  'openrouter:switchpoint/router', 'openrouter:moonshotai/kimi-k2:free', 'openrouter:moonshotai/kimi-k2',
  'openrouter:thudm/glm-4.1v-9b-thinking', 'openrouter:mistralai/devstral-medium',
  'openrouter:mistralai/devstral-small', 'openrouter:cognitivecomputations/dolphin-mistral-24b-venice-edition:free',
  'openrouter:x-ai/grok-4', 'openrouter:google/gemma-3n-e2b-it:free', 'openrouter:tencent/hunyuan-a13b-instruct',
  'openrouter:tngtech/deepseek-r1t2-chimera:free', 'openrouter:tngtech/deepseek-r1t2-chimera',
  'openrouter:morph/morph-v3-large', 'openrouter:morph/morph-v3-fast', 'openrouter:baidu/ernie-4.5-vl-424b-a47b',
  'openrouter:baidu/ernie-4.5-300b-a47b', 'openrouter:thedrummer/anubis-70b-v1.1', 'openrouter:inception/mercury',
  'openrouter:mistralai/mistral-small-3.2-24b-instruct:free', 'openrouter:mistralai/mistral-small-3.2-24b-instruct',
  'openrouter:minimax/minimax-m1', 'openrouter:google/gemini-2.5-flash', 'openrouter:google/gemini-2.5-pro',
  'openrouter:moonshotai/kimi-dev-72b', 'openrouter:openai/o3-pro', 'openrouter:x-ai/grok-3-mini',
  'openrouter:x-ai/grok-3', 'openrouter:mistralai/magistral-small-2506', 'openrouter:mistralai/magistral-medium-2506:thinking',
  'openrouter:mistralai/magistral-medium-2506', 'openrouter:google/gemini-2.5-pro-preview',
  'openrouter:deepseek/deepseek-r1-0528-qwen3-8b:free', 'openrouter:deepseek/deepseek-r1-0528-qwen3-8b',
  'openrouter:deepseek/deepseek-r1-0528:free', 'openrouter:deepseek/deepseek-r1-0528',
  'openrouter:anthropic/claude-opus-4', 'openrouter:anthropic/claude-sonnet-4', 'openrouter:mistralai/devstral-small-2505',
  'openrouter:google/gemma-3n-e4b-it:free', 'openrouter:google/gemma-3n-e4b-it', 'openrouter:openai/codex-mini',
  'openrouter:nousresearch/deephermes-3-mistral-24b-preview', 'openrouter:mistralai/mistral-medium-3',
  'openrouter:google/gemini-2.5-pro-preview-05-06', 'openrouter:arcee-ai/spotlight', 'openrouter:arcee-ai/maestro-reasoning',
  'openrouter:arcee-ai/virtuoso-large', 'openrouter:arcee-ai/coder-large', 'openrouter:microsoft/phi-4-reasoning-plus',
  'openrouter:inception/mercury-coder', 'openrouter:qwen/qwen3-4b:free', 'openrouter:deepseek/deepseek-prover-v2',
  'openrouter:meta-llama/llama-guard-4-12b', 'openrouter:qwen/qwen3-30b-a3b:free', 'openrouter:qwen/qwen3-30b-a3b',
  'openrouter:qwen/qwen3-8b', 'openrouter:qwen/qwen3-14b:free', 'openrouter:qwen/qwen3-14b',
  'openrouter:qwen/qwen3-32b', 'openrouter:qwen/qwen3-235b-a22b:free', 'openrouter:qwen/qwen3-235b-a22b',
  'openrouter:tngtech/deepseek-r1t-chimera:free', 'openrouter:tngtech/deepseek-r1t-chimera',
  'openrouter:microsoft/mai-ds-r1:free', 'openrouter:microsoft/mai-ds-r1', 'openrouter:openai/o4-mini-high',
  'openrouter:openai/o3', 'openrouter:openai/o4-mini', 'openrouter:qwen/qwen2.5-coder-7b-instruct',
  'openrouter:openai/gpt-4.1', 'openrouter:openai/gpt-4.1-mini', 'openrouter:openai/gpt-4.1-nano',
  'openrouter:eleutherai/llemma_7b', 'openrouter:alfredpros/codellama-7b-instruct-solidity',
  'openrouter:arliai/qwq-32b-arliai-rpr-v1:free', 'openrouter:arliai/qwq-32b-arliai-rpr-v1',
  'openrouter:x-ai/grok-3-mini-beta', 'openrouter:x-ai/grok-3-beta', 'openrouter:nvidia/llama-3.1-nemotron-ultra-253b-v1',
  'openrouter:meta-llama/llama-4-maverick', 'openrouter:meta-llama/llama-4-scout',
  'openrouter:qwen/qwen2.5-vl-32b-instruct:free', 'openrouter:qwen/qwen2.5-vl-32b-instruct',
  'openrouter:deepseek/deepseek-chat-v3-0324:free', 'openrouter:deepseek/deepseek-chat-v3-0324',
  'openrouter:openai/o1-pro', 'openrouter:mistralai/mistral-small-3.1-24b-instruct:free',
  'openrouter:mistralai/mistral-small-3.1-24b-instruct', 'openrouter:allenai/olmo-2-0325-32b-instruct',
  'openrouter:google/gemma-3-4b-it:free', 'openrouter:google/gemma-3-4b-it', 'openrouter:google/gemma-3-12b-it:free',
  'openrouter:google/gemma-3-12b-it', 'openrouter:cohere/command-a', 'openrouter:openai/gpt-4o-mini-search-preview',
  'openrouter:openai/gpt-4o-search-preview', 'openrouter:google/gemma-3-27b-it:free', 'openrouter:google/gemma-3-27b-it',
  'openrouter:thedrummer/skyfall-36b-v2', 'openrouter:microsoft/phi-4-multimodal-instruct',
  'openrouter:perplexity/sonar-reasoning-pro', 'openrouter:perplexity/sonar-pro',
  'openrouter:perplexity/sonar-deep-research', 'openrouter:qwen/qwq-32b', 'openrouter:google/gemini-2.0-flash-lite-001',
  'openrouter:anthropic/claude-3.7-sonnet:thinking', 'openrouter:anthropic/claude-3.7-sonnet',
  'openrouter:mistralai/mistral-saba', 'openrouter:meta-llama/llama-guard-3-8b', 'openrouter:openai/o3-mini-high',
  'openrouter:google/gemini-2.0-flash-001', 'openrouter:qwen/qwen-vl-plus', 'openrouter:aion-labs/aion-1.0',
  'openrouter:aion-labs/aion-1.0-mini', 'openrouter:aion-labs/aion-rp-llama-3.1-8b', 'openrouter:qwen/qwen-vl-max',
  'openrouter:qwen/qwen-turbo', 'openrouter:qwen/qwen2.5-vl-72b-instruct', 'openrouter:qwen/qwen-plus',
  'openrouter:qwen/qwen-max', 'openrouter:openai/o3-mini', 'openrouter:mistralai/mistral-small-24b-instruct-2501:free',
  'openrouter:mistralai/mistral-small-24b-instruct-2501', 'openrouter:deepseek/deepseek-r1-distill-qwen-32b',
  'openrouter:deepseek/deepseek-r1-distill-qwen-14b', 'openrouter:perplexity/sonar-reasoning',
  'openrouter:perplexity/sonar', 'openrouter:deepseek/deepseek-r1-distill-llama-70b:free',
  'openrouter:deepseek/deepseek-r1-distill-llama-70b', 'openrouter:deepseek/deepseek-r1:free',
  'openrouter:deepseek/deepseek-r1', 'openrouter:minimax/minimax-01', 'openrouter:mistralai/codestral-2501',
  'openrouter:microsoft/phi-4', 'openrouter:sao10k/l3.1-70b-hanami-x1', 'openrouter:deepseek/deepseek-chat',
  'openrouter:sao10k/l3.3-euryale-70b', 'openrouter:openai/o1', 'openrouter:cohere/command-r7b-12-2024',
  'openrouter:google/gemini-2.0-flash-exp:free', 'openrouter:meta-llama/llama-3.3-70b-instruct:free',
  'openrouter:meta-llama/llama-3.3-70b-instruct', 'openrouter:amazon/nova-lite-v1', 'openrouter:amazon/nova-micro-v1',
  'openrouter:amazon/nova-pro-v1', 'openrouter:openai/gpt-4o-2024-11-20', 'openrouter:mistralai/mistral-large-2411',
  'openrouter:mistralai/mistral-large-2407', 'openrouter:mistralai/pixtral-large-2411',
  'openrouter:qwen/qwen-2.5-coder-32b-instruct:free', 'openrouter:qwen/qwen-2.5-coder-32b-instruct',
  'openrouter:raifle/sorcererlm-8x22b', 'openrouter:thedrummer/unslopnemo-12b',
  'openrouter:anthropic/claude-3.5-haiku-20241022', 'openrouter:anthropic/claude-3.5-haiku',
  'openrouter:anthropic/claude-3.5-sonnet', 'openrouter:anthracite-org/magnum-v4-72b',
  'openrouter:mistralai/ministral-8b', 'openrouter:mistralai/ministral-3b',
  'openrouter:qwen/qwen-2.5-7b-instruct', 'openrouter:nvidia/llama-3.1-nemotron-70b-instruct',
  'openrouter:inflection/inflection-3-pi', 'openrouter:inflection/inflection-3-productivity',
  'openrouter:thedrummer/rocinante-12b', 'openrouter:meta-llama/llama-3.2-90b-vision-instruct',
  'openrouter:meta-llama/llama-3.2-11b-vision-instruct', 'openrouter:meta-llama/llama-3.2-1b-instruct',
  'openrouter:meta-llama/llama-3.2-3b-instruct:free', 'openrouter:meta-llama/llama-3.2-3b-instruct',
  'openrouter:qwen/qwen-2.5-72b-instruct:free', 'openrouter:qwen/qwen-2.5-72b-instruct',
  'openrouter:neversleep/llama-3.1-lumimaid-8b', 'openrouter:mistralai/pixtral-12b',
  'openrouter:cohere/command-r-plus-08-2024', 'openrouter:cohere/command-r-08-2024',
  'openrouter:sao10k/l3.1-euryale-70b', 'openrouter:qwen/qwen-2.5-vl-7b-instruct',
  'openrouter:microsoft/phi-3.5-mini-128k-instruct', 'openrouter:nousresearch/hermes-3-llama-3.1-70b',
  'openrouter:nousresearch/hermes-3-llama-3.1-405b:free', 'openrouter:nousresearch/hermes-3-llama-3.1-405b',
  'openrouter:openai/chatgpt-4o-latest', 'openrouter:sao10k/l3-lunaris-8b', 'openrouter:openai/gpt-4o-2024-08-06',
  'openrouter:meta-llama/llama-3.1-405b', 'openrouter:meta-llama/llama-3.1-405b-instruct',
  'openrouter:meta-llama/llama-3.1-70b-instruct', 'openrouter:meta-llama/llama-3.1-8b-instruct',
  'openrouter:mistralai/mistral-nemo:free', 'openrouter:mistralai/mistral-nemo',
  'openrouter:openai/gpt-4o-mini-2024-07-18', 'openrouter:openai/gpt-4o-mini', 'openrouter:google/gemma-2-27b-it',
  'openrouter:google/gemma-2-9b-it', 'openrouter:sao10k/l3-euryale-70b', 'openrouter:mistralai/mistral-7b-instruct:free',
  'openrouter:mistralai/mistral-7b-instruct', 'openrouter:mistralai/mistral-7b-instruct-v0.3',
  'openrouter:nousresearch/hermes-2-pro-llama-3-8b', 'openrouter:microsoft/phi-3-mini-128k-instruct',
  'openrouter:microsoft/phi-3-medium-128k-instruct', 'openrouter:openai/gpt-4o-2024-05-13',
  'openrouter:openai/gpt-4o', 'openrouter:openai/gpt-4o:extended', 'openrouter:meta-llama/llama-guard-2-8b',
  'openrouter:meta-llama/llama-3-70b-instruct', 'openrouter:meta-llama/llama-3-8b-instruct',
  'openrouter:mistralai/mixtral-8x22b-instruct', 'openrouter:microsoft/wizardlm-2-8x22b',
  'openrouter:openai/gpt-4-turbo', 'openrouter:anthropic/claude-3-haiku', 'openrouter:anthropic/claude-3-opus',
  'openrouter:mistralai/mistral-large', 'openrouter:openai/gpt-3.5-turbo-0613', 'openrouter:openai/gpt-4-turbo-preview',
  'openrouter:mistralai/mistral-small', 'openrouter:mistralai/mistral-tiny',
  'openrouter:mistralai/mistral-7b-instruct-v0.2', 'openrouter:mistralai/mixtral-8x7b-instruct',
  'openrouter:neversleep/noromaid-20b', 'openrouter:alpindale/goliath-120b', 'openrouter:openrouter/auto',
  'openrouter:openai/gpt-4-1106-preview', 'openrouter:openai/gpt-3.5-turbo-instruct',
  'openrouter:mistralai/mistral-7b-instruct-v0.1', 'openrouter:openai/gpt-3.5-turbo-16k',
  'openrouter:mancer/weaver', 'openrouter:undi95/remm-slerp-l2-13b', 'openrouter:gryphe/mythomax-l2-13b',
  'openrouter:openai/gpt-3.5-turbo', 'openrouter:openai/gpt-4-0314', 'openrouter:openai/gpt-4',
  
  // Worker models (80+ models - sample list)
  '@cf/pipecat-ai/smart-turn-v2', '@cf/openai/gpt-oss-120b', '@cf/qwen/qwen1.5-0.5b-chat',
  '@cf/baai/bge-m3', '@cf/huggingface/distilbert-sst-2-int8', '@cf/google/gemma-2b-it-lora',
  '@hf/nexusflow/starling-lm-7b-beta', '@cf/meta/llama-3-8b-instruct', '@cf/meta/llama-3.2-3b-instruct',
  '@hf/thebloke/llamaguard-7b-awq', '@hf/thebloke/neural-chat-7b-v3-1-awq', '@cf/meta/llama-guard-3-8b',
  '@cf/qwen/qwen3-embedding-0.6b', '@cf/meta/llama-2-7b-chat-fp16', '@cf/mistral/mistral-7b-instruct-v0.1',
  '@cf/myshell-ai/melotts', '@cf/mistral/mistral-7b-instruct-v0.2-lora', '@cf/deepgram/aura-2-es',
  '@cf/openai/whisper', '@cf/tinyllama/tinyllama-1.1b-chat-v1.0', '@cf/pfnet/plamo-embedding-1b',
  '@hf/mistral/mistral-7b-instruct-v0.2', '@cf/fblgit/una-cybertron-7b-v2-bf16',
  '@cf/llava-hf/llava-1.5-7b-hf', '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b',
  '@cf/runwayml/stable-diffusion-v1-5-inpainting', '@cf/deepgram/flux', '@cf/deepgram/nova-3',
  '@cf/black-forest-labs/flux-1-schnell', '@cf/thebloke/discolm-german-7b-v1-awq',
  '@cf/meta/llama-2-7b-chat-int8', '@cf/meta/llama-3.1-8b-instruct-fp8',
  '@hf/thebloke/mistral-7b-instruct-v0.1-awq', '@cf/qwen/qwen1.5-7b-chat-awq',
  '@cf/meta/llama-3.2-1b-instruct', '@hf/thebloke/llama-2-13b-chat-awq',
  '@cf/microsoft/resnet-50', '@cf/bytedance/stable-diffusion-xl-lightning',
  '@hf/thebloke/deepseek-coder-6.7b-base-awq', '@cf/meta-llama/llama-2-7b-chat-hf-lora',
  '@cf/meta/llama-3.3-70b-instruct-fp8-fast', '@cf/ibm-granite/granite-4.0-h-micro',
  '@cf/lykon/dreamshaper-8-lcm', '@cf/leonardo/phoenix-1.0', '@cf/stabilityai/stable-diffusion-xl-base-1.0',
  '@hf/thebloke/openhermes-2.5-mistral-7b-awq', '@cf/meta/m2m100-1.2b',
  '@cf/ai4bharat/indictrans2-en-indic-1B', '@hf/thebloke/deepseek-coder-6.7b-instruct-awq',
  '@cf/baai/bge-small-en-v1.5', '@cf/qwen/qwen2.5-coder-32b-instruct',
  '@cf/deepseek-ai/deepseek-math-7b-instruct', '@cf/tiiuae/falcon-7b-instruct',
  '@hf/nousresearch/hermes-2-pro-mistral-7b', '@cf/baai/bge-base-en-v1.5',
  '@cf/aisingapore/gemma-sea-lion-v4-27b-it', '@cf/qwen/qwen3-30b-a3b-fp8',
  '@cf/meta/llama-3.1-8b-instruct-awq', '@cf/unum/uform-gen2-qwen-500m',
  '@cf/black-forest-labs/flux-2-dev', '@hf/thebloke/zephyr-7b-beta-awq',
  '@cf/google/gemma-7b-it-lora', '@cf/qwen/qwen1.5-1.8b-chat', '@cf/mistralai/mistral-small-3.1-24b-instruct',
  '@cf/meta/llama-3-8b-instruct-awq', '@cf/meta/llama-3.2-11b-vision-instruct',
  '@cf/openai/whisper-tiny-en', '@cf/openai/whisper-large-v3-turbo', '@cf/deepgram/aura-1',
  '@cf/defog/sqlcoder-7b-2', '@cf/microsoft/phi-2', '@cf/facebook/bart-large-cnn',
  '@cf/runwayml/stable-diffusion-v1-5-img2img', '@cf/openai/gpt-oss-20b', '@cf/google/embeddinggemma-300m',
  '@cf/baai/bge-reranker-base', '@hf/google/gemma-7b-it', '@cf/leonardo/lucid-origin',
  '@cf/qwen/qwen1.5-14b-chat-awq', '@cf/openchat/openchat-3.5-0106', '@cf/meta/llama-4-scout-17b-16e-instruct',
  '@cf/google/gemma-3-12b-it', '@cf/qwen/qwq-32b', '@cf/baai/bge-large-en-v1.5',
  '@cf/deepgram/aura-2-en',
  
  // x.ai models
  'grok-4-fast-non-reasoning', 'grok-4-fast-reasoning', 'grok-code-fast-1',
];

// Helper to check if a model should route through g4f/webai
export function isG4FModel(modelId: string): boolean {
  const lowerId = modelId.toLowerCase();
  // Exclude DeepInfra models from g4f routing
  if (checkDeepInfra(modelId)) {
    return false;
  }
  return G4F_MODELS.some(model => model.toLowerCase() === lowerId || lowerId.includes(model.toLowerCase()));
}

// Helper to check if a model should route through deepinfra
export function isDeepInfraModel(modelId: string): boolean {
  return checkDeepInfra(modelId);
}

